// Exercise Data for All Phases — v2.0 (Rehab Plan v2)
// Organized by time blocks: morning, throughout_day, evening, before_bed, bonus

const exercises = {
    phase1: [
        // ============================================================
        // MORNING ROUTINE (Daily, ~10 min)
        // ============================================================
        {
            id: 'decompression_morning',
            name: '1. 90/90 Wall Decompression',
            timeBlock: 'morning',
            exerciseType: 'timed',
            timerDuration: { left: 120, right: 120 },
            targetReps: '2 min hold',
            leftTarget: 120,
            rightTarget: 120,
            sets: 1,
            bilateral: true,
            category: 'Decompression',
            instructions: {
                title: '90/90 Wall Decompression',
                steps: [
                    'Lie on back, butt against wall',
                    'Legs up wall, knees bent 90°',
                    'Press lower back into floor',
                    'Relax hip flexors completely',
                    'Hold 2 minutes',
                    'Breathe deeply throughout',
                ],
                reps: '2 minute hold',
                sets: '1 set',
                why: 'Releases overnight hip flexor tightness, decompresses spine at L5-S1',
                tips: [
                    'Lower back should be flat against floor',
                    'Let gravity do the work',
                    'Focus on deep belly breathing',
                    'Great first thing in the morning',
                ],
            },
        },
        {
            id: 'hip_flexor_morning',
            name: '2. Hip Flexor Stretch (Couch)',
            timeBlock: 'morning',
            exerciseType: 'timed',
            timerDuration: { left: 90, right: 120 },
            targetReps: 'L: 90s | R: 2min',
            leftTarget: 90,
            rightTarget: 120,
            sets: 1,
            category: 'Hip Flexor',
            instructions: {
                title: 'Hip Flexor Stretch (Couch Stretch)',
                steps: [
                    'Kneel facing away from couch/bed',
                    'Place back foot on couch (shin on couch)',
                    'Front knee at 90°',
                    'Push hips FORWARD',
                    'Squeeze GLUTE of back leg (critical!)',
                    'Keep torso upright',
                    'Feel stretch in front of hip',
                ],
                reps: 'Left: 90 seconds | Right: 2 minutes',
                sets: '1 set each side',
                why: 'Tight hip flexors pull pelvis forward causing back pain when standing',
                tips: [
                    'Squeeze back glute to deepen stretch',
                    "Don't lean forward - stay upright",
                    'Should feel strong stretch in front of hip',
                    'Right side is tighter - needs more time',
                ],
            },
        },
        {
            id: 'short_foot',
            name: '3. Short Foot Exercise',
            timeBlock: 'morning',
            exerciseType: 'reps',
            targetReps: '15 each (22 right)',
            leftTarget: 15,
            rightTarget: 22,
            sets: 3,
            category: 'Foot & Ankle',
            instructions: {
                title: 'Short Foot Exercise (Arch Activation)',
                steps: [
                    'Sit on edge of bed, feet flat on floor',
                    'Pull arch UP without curling toes',
                    'Think: "Make foot shorter"',
                    'Hold for 5 seconds',
                    'Release and repeat',
                ],
                reps: '15 each foot (22 right foot)',
                sets: '3 sets each foot',
                why: 'Activates intrinsic foot muscles for arch support',
                tips: [
                    'Do barefoot',
                    'NO toe curling - toes stay relaxed',
                    'You should see arch lift',
                    'Foot should visibly shorten',
                ],
            },
        },
        {
            id: 'standing_posture_morning',
            name: '4. Standing Posture Practice',
            timeBlock: 'morning',
            exerciseType: 'timed',
            timerDuration: { left: 120, right: 120 },
            targetReps: '2 min hold',
            leftTarget: 120,
            rightTarget: 120,
            sets: 1,
            bilateral: true,
            category: 'Posture',
            progression: {
                1: { left: 120, right: 120 },
                2: { left: 300, right: 300 },
                3: { left: 600, right: 600 },
            },
            instructions: {
                title: 'Standing Posture Practice',
                steps: [
                    'Stand with feet hip-width apart',
                    'Unlock knees (slight bend)',
                    'Tuck pelvis slightly: "Zipper pulling up"',
                    'Squeeze glutes lightly (20%)',
                    'Engage core (30%): "Ribs down"',
                    'Shoulders back and down',
                    'Hold this position',
                ],
                reps: 'Week 1: 2 min | Week 2: 5 min | Week 3: 10 min',
                sets: '1 set',
                why: 'Your default standing posture causes pain - this retrains it',
                tips: [
                    'You should be able to breathe normally',
                    'Feel lower back flatten slightly',
                    'Build standing tolerance without back pain',
                    'Practice in front of mirror initially',
                ],
            },
        },

        // ============================================================
        // THROUGHOUT THE DAY (Quick-log, every 20-60 min)
        // ============================================================
        {
            id: 'hip_flexor_quick',
            name: 'Hip Flexor Stretch',
            timeBlock: 'throughout_day',
            exerciseType: 'quick_log',
            targetReps: 'Every 30 min sitting',
            leftTarget: 60,
            rightTarget: 90,
            sets: 1,
            category: 'Hip Flexor',
            quickLogTarget: 10,
            quickLogUnit: 'times',
            quickLogReminder: 'Every 30 min of sitting',
            instructions: {
                title: 'Hip Flexor Stretch (Throughout Day)',
                steps: [
                    'Kneeling lunge position',
                    'Back knee on cushion/pad',
                    'Front knee at 90°',
                    'Push hips forward',
                    'Squeeze back glute',
                    'Keep torso upright',
                    'Hold 60 sec left, 90 sec right',
                ],
                reps: 'Left: 60 sec | Right: 90 sec',
                sets: 'After every 30 minutes of sitting',
                why: 'Prevents hip flexor tightening that causes standing pain',
                tips: [
                    'This is the #1 priority throughout the day',
                    'Set a timer to remind you',
                    "Don't skip this - it fixes standing pain",
                    'Even 30 seconds helps',
                ],
            },
        },
        {
            id: 'glute_activation_quick',
            name: 'Glute Activation Drill',
            timeBlock: 'throughout_day',
            exerciseType: 'quick_log',
            targetReps: 'Every time you stand',
            leftTarget: 10,
            rightTarget: 10,
            sets: 1,
            bilateral: true,
            category: 'Glute Med',
            quickLogTarget: 20,
            quickLogUnit: 'times',
            quickLogReminder: 'Every time you stand up',
            instructions: {
                title: 'Glute Activation Drill',
                steps: [
                    'Stand up from chair',
                    'IMMEDIATELY squeeze both glutes (50% effort)',
                    'Tuck pelvis slightly',
                    'Feel lower back flatten',
                    'Hold 10 seconds',
                    'Release to 20% activation',
                    'Maintain while standing',
                ],
                reps: '10 second hold',
                sets: 'Every single time you stand (20-30x per day)',
                why: 'Teaches glutes to turn on automatically when standing',
                tips: [
                    'Make this a habit - every time you stand',
                    'Should become automatic within 2 weeks',
                    'The squeeze should be immediate',
                    'Feel your posture improve instantly',
                ],
            },
        },
        {
            id: 'standing_posture_quick',
            name: 'Standing Posture Practice',
            timeBlock: 'throughout_day',
            exerciseType: 'quick_log',
            targetReps: '10x per day, 2-5 min each',
            leftTarget: 120,
            rightTarget: 120,
            sets: 1,
            bilateral: true,
            category: 'Posture',
            quickLogTarget: 10,
            quickLogUnit: 'practices',
            quickLogReminder: 'Brushing teeth, waiting, elevator, etc.',
            instructions: {
                title: 'Standing Posture Practice (Throughout Day)',
                steps: [
                    'Whenever you find yourself standing:',
                    'Unlock knees (slight bend)',
                    'Tuck pelvis slightly',
                    'Squeeze glutes lightly (20%)',
                    'Engage core (30%)',
                    'Shoulders back and down',
                    'Hold for 2-5 minutes',
                ],
                reps: 'Week 1: 2 min | Week 2: 5 min | Week 3: 10 min',
                sets: '10 practices per day',
                why: 'Builds standing tolerance without back pain',
                tips: [
                    'Brushing teeth = 2 min practice',
                    'Waiting for coffee = 3 min',
                    'Elevator = 1-2 min',
                    'Grocery line = 3-5 min',
                ],
            },
        },
        {
            id: 'seated_clamshells_quick',
            name: 'Seated Clamshells',
            timeBlock: 'throughout_day',
            exerciseType: 'quick_log',
            targetReps: 'Every 20 min at desk',
            leftTarget: 20,
            rightTarget: 30,
            sets: 1,
            category: 'Glute Med',
            quickLogTarget: 15,
            quickLogUnit: 'times',
            quickLogReminder: 'Every 20 min at desk',
            instructions: {
                title: 'Seated Clamshells at Desk',
                steps: [
                    'Sit on edge of chair',
                    'Feet flat, hip-width apart',
                    'Knees slightly apart (10cm gap)',
                    'Keep feet planted',
                    'Push knees APART against invisible resistance',
                    'Feel SIDE of hips work',
                    'Hold 3 seconds',
                    'Repeat: 20 left, 30 right',
                ],
                reps: 'Left: 20 | Right: 30',
                sets: '1 set every 20 minutes at desk',
                why: 'Prevents glute med from shutting down during sitting',
                tips: [
                    'No one will notice you doing this',
                    'Push outward, not just apart',
                    'Feel the burn in side of hips',
                    'Great during meetings or calls',
                ],
            },
        },

        // ============================================================
        // EVENING WORKOUT (Daily except Wed/Sun, 25-30 min)
        // ============================================================
        {
            id: 'hip_flexor_warmup',
            name: '1. Hip Flexor Stretch (Warm-up)',
            timeBlock: 'evening',
            exerciseType: 'timed',
            timerDuration: { left: 90, right: 120 },
            targetReps: 'L: 90s | R: 2min',
            leftTarget: 90,
            rightTarget: 120,
            sets: 1,
            category: 'Hip Flexor',
            instructions: {
                title: 'Hip Flexor Stretch (Pre-Workout)',
                steps: [
                    'Kneeling lunge position (or couch stretch)',
                    'Back knee on cushion/pad',
                    'Front knee at 90°',
                    'Push hips forward',
                    'Squeeze back glute',
                    'Keep torso upright',
                    'Hold 90 sec left, 2 min right',
                ],
                reps: 'Left: 90 seconds | Right: 2 minutes',
                sets: '1 set each side',
                why: 'Pre-workout hip flexor release to protect L5-S1',
                tips: [
                    'Same technique as morning couch stretch',
                    'Can be done kneeling on floor instead',
                    'Squeeze back glute to deepen stretch',
                    'Breathe deeply',
                ],
            },
        },
        {
            id: 'dead_bug_holds',
            name: '2. Dead Bug Holds',
            timeBlock: 'evening',
            exerciseType: 'timed_holds',
            timerDuration: { left: 10, right: 15 },
            targetReps: '6 holds each side',
            leftTarget: 6,
            rightTarget: 6,
            sets: 1,
            category: 'Core',
            progression: {
                1: { left: 10, right: 15 },
                3: { left: 15, right: 20 },
                5: { left: 20, right: 30 },
            },
            instructions: {
                title: 'Dead Bug Holds (Core Endurance)',
                steps: [
                    'Lie on back, arms straight up',
                    'Knees at 90° (tabletop)',
                    'Press lower back into floor (CRITICAL)',
                    'Lower RIGHT arm + LEFT leg (hold)',
                    'Return to start',
                    'Lower LEFT arm + RIGHT leg (hold longer)',
                    'Return to start, repeat',
                ],
                reps: 'LEFT side: 10s holds | RIGHT side: 15s holds × 6 each',
                sets: '1 set (6 holds per side)',
                why: 'RIGHT core is weaker - extra hold time builds endurance asymmetrically',
                tips: [
                    'Lower back NEVER leaves floor',
                    "If back arches, don't go as low",
                    'Breathe normally during holds',
                    'RIGHT side working harder = fixing imbalance',
                ],
            },
        },
        {
            id: 'clamshells',
            name: '3. Clamshells',
            timeBlock: 'evening',
            exerciseType: 'reps',
            targetReps: '20 each (30 right)',
            leftTarget: 20,
            rightTarget: 30,
            sets: 3,
            category: 'Glute Med',
            instructions: {
                title: 'Clamshells (Glute Med Isolation)',
                steps: [
                    'Lie on LEFT side first (works RIGHT glute med)',
                    'Knees bent 90°',
                    'Stack hips directly on top of each other',
                    'Keep feet together',
                    'Lift top knee as high as possible',
                    'Squeeze glutes at top, hold 2 seconds',
                    'Lower with control',
                    'Complete 30 reps RIGHT, then 20 reps LEFT',
                ],
                reps: 'Left: 20 | Right: 30',
                sets: '3 sets',
                why: 'RIGHT glute med is weaker - more reps = more activation',
                tips: [
                    "Don't roll hips back",
                    'Feet stay glued together',
                    'Feel it in SIDE of hip',
                    'RIGHT side will fatigue more (good!)',
                ],
            },
        },
        {
            id: 'supine_glute_med',
            name: '4. Supine Glute Med (Band Push-Aparts)',
            timeBlock: 'evening',
            exerciseType: 'reps',
            targetReps: '20 each (30 right)',
            leftTarget: 20,
            rightTarget: 30,
            sets: 3,
            category: 'Glute Med',
            instructions: {
                title: 'Supine Glute Med Activation (Band Push-Aparts)',
                steps: [
                    'Lie on back, both knees bent',
                    'Feet flat on floor',
                    'Place resistance band above knees (or use hands)',
                    'Push knees APART against band',
                    'Feel SIDE of hips working',
                    'Hold 5 seconds at max width',
                    'Control return',
                    'Repeat',
                ],
                reps: 'Left: 20 | Right: 30',
                sets: '3 sets',
                why: 'Activates glute med with zero back stress',
                tips: [
                    'Keep lower back pressed into floor',
                    'Push knees apart, not just open',
                    'Feel burn in side of hips',
                    'Can use hands for resistance if no band',
                ],
            },
        },
        {
            id: 'glute_bridges',
            name: '5. Glute Bridges (Both Legs)',
            timeBlock: 'evening',
            exerciseType: 'reps',
            targetReps: '20',
            leftTarget: 20,
            rightTarget: 20,
            sets: 3,
            bilateral: true,
            category: 'Hip & Glute',
            instructions: {
                title: 'Glute Bridges (Both Legs)',
                steps: [
                    'Lie on back, knees bent, feet flat',
                    'Feet hip-width apart',
                    'Press through heels, lift hips up',
                    'Form straight line from shoulders to knees',
                    'Squeeze glutes HARD at top',
                    'Hold 3 seconds',
                    'Lower with control',
                ],
                reps: '20',
                sets: '3 sets',
                why: 'Builds posterior chain strength, safe for L5-S1',
                tips: [
                    "Don't arch lower back at top",
                    'Push through heels, not toes',
                    'Squeeze glutes, not hamstrings',
                    'Breathe at top',
                ],
            },
        },
        {
            id: 'single_leg_bridge',
            name: '6. Single-Leg Glute Bridge',
            timeBlock: 'evening',
            exerciseType: 'reps',
            targetReps: '12 each (18 right)',
            leftTarget: 12,
            rightTarget: 18,
            sets: 3,
            category: 'Hamstring',
            instructions: {
                title: 'Single-Leg Glute Bridge (Hamstring + Glute)',
                steps: [
                    'Lie on back, LEFT knee bent, foot flat',
                    'Extend RIGHT leg straight',
                    'Press through LEFT heel, lift hips',
                    "Keep hips level - don't let them drop",
                    'Squeeze RIGHT glute at top',
                    'Hold 2 seconds',
                    'Lower and repeat',
                    'Complete 18 reps RIGHT, then 12 LEFT',
                ],
                reps: 'Left: 12 | Right: 18',
                sets: '3 sets',
                why: 'RIGHT hamstring weaker - extra volume corrects asymmetry',
                tips: [
                    'RIGHT side will be MUCH harder (expected!)',
                    'Keep hips perfectly level',
                    'Extended leg stays straight',
                    'Drive through heel of grounded foot',
                ],
            },
        },
        {
            id: 'prone_hamstring_curls',
            name: '7. Prone Hamstring Curls',
            timeBlock: 'evening',
            exerciseType: 'reps',
            targetReps: '15 each (22 right)',
            leftTarget: 15,
            rightTarget: 22,
            sets: 3,
            category: 'Hamstring',
            instructions: {
                title: 'Prone Hamstring Curls (Hamstring Isolation)',
                steps: [
                    'Lie face down on floor/bed',
                    'Forehead on hands',
                    'Start with RIGHT leg (weaker)',
                    'Bend RIGHT knee, bring heel toward butt',
                    'Squeeze hamstring at top',
                    'Hold 2 seconds',
                    'Lower slowly (4 seconds)',
                    'Complete 22 reps RIGHT, then 15 LEFT',
                ],
                reps: 'Left: 15 | Right: 22',
                sets: '3 sets',
                why: 'RIGHT hamstring needs extra work - builds strength asymmetrically',
                tips: [
                    'Slow the lowering phase (4 seconds)',
                    'Squeeze hard at the top',
                    'Keep hips pressed into floor',
                    'Week 3+: add ankle weights or resistance band',
                ],
            },
        },
        {
            id: 'hip_abduction',
            name: '8. Side-Lying Hip Abduction',
            timeBlock: 'evening',
            exerciseType: 'reps',
            targetReps: '15 each (22 right)',
            leftTarget: 15,
            rightTarget: 22,
            sets: 3,
            category: 'Glute Med',
            instructions: {
                title: 'Side-Lying Hip Abduction (Glute Med)',
                steps: [
                    'Lie on LEFT side (works RIGHT glute med)',
                    'Bottom leg bent for stability',
                    'Top leg (RIGHT) straight',
                    'Toes pointing FORWARD (not up)',
                    'Lift leg up toward ceiling (30cm max)',
                    "Keep hips stacked - don't roll back",
                    'Hold 2 seconds at top',
                    'Lower with control',
                    'Complete 22 reps RIGHT, then 15 LEFT',
                ],
                reps: 'Left: 15 | Right: 22',
                sets: '3 sets',
                why: 'RIGHT glute med weaker - more reps = better activation',
                tips: [
                    'Toes forward, not toward ceiling',
                    "Don't go too high - quality over height",
                    'Feel burn in SIDE of hip',
                    'Keep body in straight line',
                ],
            },
        },
        {
            id: 'bird_dog_holds',
            name: '9. Bird Dog Holds',
            timeBlock: 'evening',
            exerciseType: 'timed_holds',
            timerDuration: { left: 15, right: 20 },
            targetReps: '3 holds each side',
            leftTarget: 3,
            rightTarget: 3,
            sets: 3,
            category: 'Core',
            progression: {
                1: { left: 15, right: 20, note: 'Arm only (no leg extension)' },
                2: { left: 15, right: 20, note: 'Leg only (no arm extension)' },
                3: { left: 15, right: 20, note: 'Opposite arm + leg' },
            },
            instructions: {
                title: 'Bird Dog Holds (Core + Posterior Chain)',
                steps: [
                    'Start on hands and knees (tabletop)',
                    'Hands under shoulders, knees under hips',
                    'Extend LEFT arm + RIGHT leg (works RIGHT core) - Hold 20 sec',
                    'Keep hips level, no rotation',
                    'Return, switch sides',
                    'Extend RIGHT arm + LEFT leg - Hold 15 sec',
                    'Return, repeat',
                ],
                reps: 'LEFT core: 15s holds | RIGHT core: 20s holds × 3 each',
                sets: '3 sets each combination',
                why: 'RIGHT core weaker - longer hold times build endurance',
                tips: [
                    "Don't let hips rotate or drop",
                    'Back stays flat, no sagging',
                    'Look down to keep neck neutral',
                    'Week 1: arm only, Week 2: leg only, Week 3+: full',
                ],
            },
        },
        {
            id: 'plank',
            name: '10. Plank',
            timeBlock: 'evening',
            exerciseType: 'timed',
            timerDuration: { left: 30, right: 30 },
            targetReps: '30 sec',
            leftTarget: 30,
            rightTarget: 30,
            sets: 3,
            bilateral: true,
            category: 'Core',
            progression: {
                1: { left: 30, right: 30, note: 'Knees down' },
                2: { left: 45, right: 45, note: 'Knees down' },
                3: { left: 60, right: 60, note: 'Knees down' },
                4: { left: 20, right: 20, note: 'Full plank (toes)' },
                5: { left: 30, right: 30, note: 'Full plank (toes)' },
                6: { left: 45, right: 45, note: 'Full plank (toes)' },
                7: { left: 60, right: 60, note: 'Full plank (toes)' },
            },
            instructions: {
                title: 'Plank (Core Endurance)',
                steps: [
                    'Forearms on ground, elbows under shoulders',
                    'Knees down (modified plank) for Weeks 1-3',
                    'Body in straight line from head to knees',
                    'Engage core (30%)',
                    'Squeeze glutes (20%)',
                    'Hold position, breathe normally',
                ],
                reps: 'Week 1: 30s | Week 2: 45s | Week 3: 60s (knees)',
                sets: '3 sets',
                why: 'Builds core endurance for standing tolerance',
                tips: [
                    "Don't let hips sag",
                    "Don't pike hips up",
                    'Stop if back hurts',
                    'Week 4+: transition to full plank from toes',
                ],
            },
        },
        {
            id: 'balance_wall',
            name: '11. Single-Leg Balance (Wall Support)',
            timeBlock: 'evening',
            exerciseType: 'timed',
            timerDuration: { left: 30, right: 45 },
            targetReps: 'L: 30s | R: 45s',
            leftTarget: 30,
            rightTarget: 45,
            sets: 3,
            category: 'Balance',
            instructions: {
                title: 'Single-Leg Balance (Wall Support)',
                steps: [
                    'Stand near wall or chair',
                    'Stand on RIGHT leg first (weaker)',
                    'Touch wall lightly with fingertips',
                    'Keep eyes open, focus on fixed point',
                    'Engage RIGHT glute med (feel side of hip)',
                    'Hold 45 seconds',
                    'Rest, switch legs',
                    'Stand on LEFT leg: 30 seconds',
                ],
                reps: 'Left: 30 sec | Right: 45 sec',
                sets: '3 sets each leg',
                why: 'RIGHT side needs more balance/proprioception work',
                tips: [
                    'Start with 2-3 fingers on wall',
                    'Progress to 1 finger as you improve',
                    'Keep hips level',
                    'RIGHT side will wobble more (normal)',
                ],
            },
        },
        {
            id: 'decompression_cooldown',
            name: '12. 90/90 Decompression (Cool-down)',
            timeBlock: 'evening',
            exerciseType: 'timed',
            timerDuration: { left: 150, right: 150 },
            targetReps: '2-3 min hold',
            leftTarget: 150,
            rightTarget: 150,
            sets: 1,
            bilateral: true,
            category: 'Decompression',
            instructions: {
                title: '90/90 Wall Decompression (Cool-down)',
                steps: [
                    'Lie on back, butt against wall',
                    'Legs up wall, knees bent 90°',
                    'Press lower back into floor',
                    'Relax hip flexors completely',
                    'Hold 2-3 minutes',
                    'Breathe deeply throughout',
                ],
                reps: '2-3 minute hold',
                sets: '1 set',
                why: 'Releases any hip flexor tightness from workout, decompresses L5-S1',
                tips: [
                    'Same as morning routine',
                    'Great cool-down after workout',
                    'Focus on relaxation',
                    'Let spine decompress naturally',
                ],
            },
        },

        // ============================================================
        // BEFORE BED (Daily, ~5 min)
        // ============================================================
        {
            id: 'hip_flexor_bed',
            name: '1. Hip Flexor Stretch (Before Bed)',
            timeBlock: 'before_bed',
            exerciseType: 'timed',
            timerDuration: { left: 60, right: 90 },
            targetReps: 'L: 60s | R: 90s',
            leftTarget: 60,
            rightTarget: 90,
            sets: 1,
            category: 'Hip Flexor',
            instructions: {
                title: 'Hip Flexor Stretch (Before Bed)',
                steps: [
                    'Kneeling lunge position',
                    'Back knee on cushion/pad',
                    'Front knee at 90°',
                    'Push hips forward',
                    'Squeeze back glute',
                    'Keep torso upright',
                    'Hold 60 sec left, 90 sec right',
                ],
                reps: 'Left: 60 sec | Right: 90 sec',
                sets: '1 set each side',
                why: 'Final release before sleep prevents morning tightness',
                tips: [
                    'Gentle stretch - not aggressive before bed',
                    'Focus on breathing and relaxation',
                    'Right side gets extra time',
                    'Should feel pleasant, not painful',
                ],
            },
        },
        {
            id: 'decompression_bed',
            name: '2. 90/90 Wall Position (Before Bed)',
            timeBlock: 'before_bed',
            exerciseType: 'timed',
            timerDuration: { left: 120, right: 120 },
            targetReps: '2 min hold',
            leftTarget: 120,
            rightTarget: 120,
            sets: 1,
            bilateral: true,
            category: 'Decompression',
            instructions: {
                title: '90/90 Wall Position (Before Bed)',
                steps: [
                    'Lie on back, butt against wall',
                    'Legs up wall, knees bent 90°',
                    'Press lower back into floor',
                    'Relax completely',
                    'Hold 2 minutes',
                    'Breathe deeply',
                ],
                reps: '2 minute hold',
                sets: '1 set',
                why: 'Decompresses spine before sleep, promotes recovery',
                tips: [
                    'Same as morning routine',
                    'Great for winding down',
                    'Can do in bed against headboard',
                    'Focus on deep breathing',
                ],
            },
        },

        // ============================================================
        // BONUS (Optional exercises from previous plan)
        // ============================================================
        {
            id: 'toe_yoga',
            name: 'Toe Yoga',
            timeBlock: 'bonus',
            exerciseType: 'reps',
            targetReps: '10 each direction',
            leftTarget: 10,
            rightTarget: 15,
            sets: 2,
            category: 'Foot & Ankle',
            instructions: {
                title: 'Toe Yoga (Toe Control)',
                steps: [
                    'Sit with feet flat on floor',
                    'Movement 1: Lift big toe only, keep other 4 toes down',
                    'Hold 2 seconds, release',
                    'Movement 2: Keep big toe down, lift other 4 toes',
                    'Hold 2 seconds, release',
                    'Alternate between movements',
                ],
                reps: '10 each direction, each foot (15 right)',
                sets: '2 sets',
                why: 'Improves individual toe control and arch stability',
                tips: [
                    'Do barefoot',
                    'Start slowly - this is HARD at first',
                    'Use your fingers to help initially if needed',
                    'Focus on isolating toe muscles',
                ],
            },
        },
        {
            id: 'towel_scrunch',
            name: 'Towel Scrunches',
            timeBlock: 'bonus',
            exerciseType: 'reps',
            targetReps: '20 each foot',
            leftTarget: 20,
            rightTarget: 30,
            sets: 2,
            category: 'Foot & Ankle',
            instructions: {
                title: 'Towel Scrunches',
                steps: [
                    'Place small towel flat on floor',
                    'Sit with bare feet on towel edge',
                    'Use toes to grip towel',
                    'Scrunch towel toward you',
                    'Release and reposition',
                    'Repeat until towel is bunched up',
                ],
                reps: '20 scrunches per foot (30 right)',
                sets: '2 sets',
                why: 'Strengthens foot flexors and arch muscles',
                tips: [
                    'Keep heel planted on ground',
                    'Use only toes to grip',
                    'Make sure arch stays engaged',
                    'Can add weight on towel for progression',
                ],
            },
        },
        {
            id: 'calf_raises',
            name: 'Calf Raises',
            timeBlock: 'bonus',
            exerciseType: 'reps',
            targetReps: '15-20',
            leftTarget: 15,
            rightTarget: 22,
            sets: 3,
            category: 'Foot & Ankle',
            instructions: {
                title: 'Calf Raises',
                steps: [
                    'Stand on edge of step (or flat floor)',
                    'Rise up on toes as high as possible',
                    'Hold at top for 2 seconds',
                    'Lower slowly, below step level if on step',
                    'Control the descent',
                ],
                reps: '15-20 (both feet or single leg)',
                sets: '3 sets',
                why: 'Supports arch, strengthens posterior chain, builds ankle stability',
                tips: [
                    'Full range of motion',
                    'Slow and controlled',
                    'Hold at top for 2 seconds',
                    'Progress to single leg',
                ],
            },
        },
        {
            id: 'ankle_mobility',
            name: 'Ankle Mobility',
            timeBlock: 'bonus',
            exerciseType: 'reps',
            targetReps: '15 each side',
            leftTarget: 15,
            rightTarget: 22,
            sets: 1,
            category: 'Mobility',
            instructions: {
                title: 'Ankle Mobility (Dorsiflexion)',
                steps: [
                    'Face wall, stand about 6 inches away',
                    'Place one foot forward',
                    'Push knee toward wall',
                    'Keep heel DOWN on floor',
                    'Feel stretch in calf and ankle',
                    'Hold 2 seconds, return',
                    'Repeat 15 times',
                ],
                reps: '15 each side',
                sets: '1 set',
                why: 'Limited ankle mobility causes compensations throughout chain',
                tips: [
                    'Heel MUST stay down',
                    'If heel lifts, move closer to wall',
                    'Aim to touch wall with knee',
                    'Do daily, especially before exercise',
                ],
            },
        },
        {
            id: 'piriformis_stretch',
            name: 'Piriformis Stretch',
            timeBlock: 'bonus',
            exerciseType: 'reps',
            targetReps: '30 sec hold',
            leftTarget: 30,
            rightTarget: 30,
            sets: 3,
            category: 'Mobility',
            instructions: {
                title: 'Piriformis Stretch (Figure-4)',
                steps: [
                    'Lie on back',
                    'Cross right ankle over left knee (figure-4)',
                    'Thread hands behind left thigh',
                    'Pull left knee toward chest',
                    'Feel stretch in right glute',
                    'Hold 30 seconds',
                    'Switch sides',
                ],
                reps: '30 seconds each side',
                sets: '3 sets',
                why: 'Relieves pressure on sciatic nerve, releases deep hip rotators',
                tips: [
                    'Keep crossed ankle flexed',
                    'Pull toward chest, not to side',
                    'Relax into stretch',
                    'Should feel deep in glute',
                ],
            },
        },
    ],

    phase2: [
        // Phase 2 exercises kept intact but hidden in UI until updated
        {
            id: 'step_ups',
            name: '16. Step-Ups',
            targetReps: '12 each (18 right)',
            leftTarget: 12,
            rightTarget: 18,
            sets: 3,
            category: 'Single-Leg Strength',
            timeBlock: 'evening',
            exerciseType: 'reps',
            instructions: {
                title: 'Step-Ups',
                steps: [
                    'Use a step or box 6-12 inches high',
                    'Place right foot fully on step',
                    'Push through right heel to step up',
                    'Bring left foot up to meet right',
                    'Step down with control, left foot first',
                    'Repeat for all reps, then switch legs',
                ],
                reps: '12 each leg (18 right)',
                sets: '3 sets',
                why: 'Builds single-leg strength, improves balance',
                tips: [
                    'Drive through heel of elevated foot',
                    'Keep chest up, core engaged',
                    'Step down slowly',
                    'Start with lower step, progress higher',
                ],
            },
        },
        {
            id: 'split_squats',
            name: '17. Split Squats (Bulgarian)',
            targetReps: '10 each (15 right)',
            leftTarget: 10,
            rightTarget: 15,
            sets: 3,
            category: 'Single-Leg Strength',
            timeBlock: 'evening',
            exerciseType: 'reps',
            instructions: {
                title: 'Bulgarian Split Squats',
                steps: [
                    'Stand facing away from bench/chair',
                    'Place top of back foot on bench',
                    'Front foot 2-3 feet in front',
                    'Lower down by bending front knee',
                    'Back knee drops toward floor',
                    'Push through front heel to stand',
                ],
                reps: '10 each leg (15 right)',
                sets: '3 sets',
                why: 'Elite single-leg strength builder',
                tips: [
                    'Start bodyweight only',
                    'Front knee tracks over toes',
                    'Chest stays up',
                    'Back leg is just for balance',
                ],
            },
        },
        {
            id: 'single_leg_deadlift',
            name: '18. Single-Leg Deadlift',
            targetReps: '10 each (15 right)',
            leftTarget: 10,
            rightTarget: 15,
            sets: 3,
            category: 'Single-Leg Strength',
            timeBlock: 'evening',
            exerciseType: 'reps',
            instructions: {
                title: 'Single-Leg Deadlift (RDL)',
                steps: [
                    'Stand on one leg, slight bend in knee',
                    'Hinge at hips, reaching forward',
                    'Back leg extends straight behind',
                    'Keep back flat, core tight',
                    'Reach hand toward floor',
                    'Pull back up using glute and hamstring',
                ],
                reps: '10 each leg (15 right)',
                sets: '3 sets',
                why: 'Challenges balance, builds posterior chain',
                tips: [
                    'Start holding wall for support',
                    'Hinge at hips, not round the back',
                    'Move slowly and controlled',
                    'Add weight when form is perfect',
                ],
            },
        },
        {
            id: 'lateral_band_walks',
            name: '19. Lateral Band Walks',
            targetReps: '15 steps each way',
            leftTarget: 15,
            rightTarget: 22,
            sets: 3,
            category: 'Dynamic Stability',
            timeBlock: 'evening',
            exerciseType: 'reps',
            instructions: {
                title: 'Lateral Band Walks',
                steps: [
                    'Place resistance band above knees',
                    'Stand with feet hip-width apart',
                    'Slight bend in knees, hips back',
                    'Step sideways with right foot',
                    'Follow with left foot, maintaining tension',
                    'Take 15 steps each direction',
                ],
                reps: '15 steps each direction (22 right)',
                sets: '3 sets',
                why: 'Activates glute med dynamically',
                tips: [
                    'Keep knees pushing out against band',
                    'Stay low in athletic stance',
                    'Feel burn in side of glutes',
                    'Constant tension',
                ],
            },
        },
        {
            id: 'balance_reaches',
            name: '20. Single-Leg Balance Reaches',
            targetReps: '8 each direction',
            leftTarget: 8,
            rightTarget: 12,
            sets: 2,
            category: 'Dynamic Stability',
            timeBlock: 'evening',
            exerciseType: 'reps',
            instructions: {
                title: 'Single-Leg Balance Reaches',
                steps: [
                    'Stand on one leg',
                    'Reach other leg forward, tap toe',
                    'Return to center',
                    'Reach to the side, tap',
                    'Return to center',
                    'Reach backward, tap',
                    'Return to center',
                ],
                reps: '8 reaches per direction (12 right)',
                sets: '2 sets',
                why: 'Dynamic balance challenge, trains stability in multiple planes',
                tips: [
                    'Standing leg stays slightly bent',
                    'Just tap with toe - light touch',
                    'Control the movement',
                    'Keep hips level throughout',
                ],
            },
        },
        {
            id: 'goblet_squats',
            name: '21. Goblet Squats',
            targetReps: '12-15',
            leftTarget: 12,
            rightTarget: 12,
            sets: 3,
            bilateral: true,
            category: 'Controlled Loading',
            timeBlock: 'evening',
            exerciseType: 'reps',
            instructions: {
                title: 'Goblet Squats',
                steps: [
                    'Hold dumbbell or kettlebell at chest',
                    'Feet shoulder-width apart, toes slightly out',
                    'Keep chest up, core braced',
                    'Sit back and down, weight in heels',
                    'Descend until thighs parallel',
                    'Drive through heels to stand',
                ],
                reps: '12-15',
                sets: '3 sets',
                why: 'Safe squat progression, bilateral leg strength',
                tips: [
                    'Weight at chest helps keep torso upright',
                    'Start light (10-20 lbs)',
                    'Knees track over toes',
                    'Full depth only if comfortable',
                ],
            },
        },
    ],

    phase3: [
        // Phase 3 exercises kept intact but hidden in UI until updated
        {
            id: 'box_step_ups',
            name: '22. Box Step-Ups with Knee Drive',
            targetReps: '10 each (15 right)',
            leftTarget: 10,
            rightTarget: 15,
            sets: 3,
            category: 'Power & Plyometrics',
            timeBlock: 'evening',
            exerciseType: 'reps',
            instructions: {
                title: 'Box Step-Ups with Knee Drive',
                steps: [
                    'Use sturdy box (12-18 inches)',
                    'Place right foot fully on box',
                    'Explosively push through right heel',
                    'Drive left knee up toward chest',
                    'Stand tall at top',
                    'Step down with control',
                ],
                reps: '10 each leg (15 right)',
                sets: '3 sets',
                why: 'Builds explosive power, mimics running mechanics',
                tips: [
                    'Explosive drive up, controlled descent',
                    'Land softly when stepping down',
                    'Knee drive is key',
                    'All power from elevated leg',
                ],
            },
        },
        {
            id: 'single_leg_hops',
            name: '23. Single-Leg Hops',
            targetReps: '5-8 per direction',
            leftTarget: 5,
            rightTarget: 8,
            sets: 3,
            category: 'Power & Plyometrics',
            timeBlock: 'evening',
            exerciseType: 'reps',
            instructions: {
                title: 'Single-Leg Hops',
                steps: [
                    'Stand on one leg',
                    'Hop forward, landing on same leg',
                    'Absorb landing with bent knee',
                    'Immediately hop again',
                    'Complete 5-8 hops forward',
                    'Then hop backward, sideways',
                ],
                reps: '5-8 hops per direction (8 right)',
                sets: '3 sets',
                why: 'Plyometric training - builds reactive strength',
                tips: [
                    'Land softly with quiet feet',
                    'Knee should track straight',
                    'Start with small hops',
                    'Stop if pain develops',
                ],
            },
        },
        {
            id: 'farmers_carries',
            name: "24. Farmer's Carries",
            targetReps: '20m each side',
            leftTarget: 20,
            rightTarget: 20,
            sets: 3,
            bilateral: true,
            category: 'Power & Plyometrics',
            timeBlock: 'evening',
            exerciseType: 'reps',
            instructions: {
                title: "Farmer's Carries",
                steps: [
                    'Hold heavy dumbbell in one hand',
                    'Stand tall, shoulders back',
                    'Core braced, ribs down',
                    'Walk forward for 20 meters',
                    "Don't let body lean to weighted side",
                    'Keep shoulders level',
                    'Turn around, walk back',
                    'Switch hands, repeat',
                ],
                reps: '20 meters per side',
                sets: '3 sets',
                why: 'Unilateral load challenges core stability',
                tips: [
                    'Use challenging weight',
                    'Walk with normal gait',
                    'Squeeze handle hard',
                    'Fight the lean - stay upright',
                ],
            },
        },
    ],
};

/** Time block display names and order */
const TIME_BLOCKS = {
    morning: { label: 'Morning', shortLabel: 'AM', order: 0 },
    throughout_day: { label: 'Throughout Day', shortLabel: 'Day', order: 1 },
    evening: { label: 'Evening', shortLabel: 'PM', order: 2 },
    before_bed: { label: 'Before Bed', shortLabel: 'Bed', order: 3 },
    bonus: { label: 'Bonus', shortLabel: 'Extra', order: 4 },
};

// Get exercises for a specific phase (all time blocks)
function getExercisesForPhase(phase) {
    switch (phase) {
        case 1:
            return exercises.phase1;
        case 2:
            return [...exercises.phase1, ...exercises.phase2];
        case 3:
            return [...exercises.phase1, ...exercises.phase2, ...exercises.phase3];
        default:
            return exercises.phase1;
    }
}

/**
 * Get exercises filtered by phase and time block.
 * @param {number} phase - Phase number (1, 2, or 3)
 * @param {string} timeBlock - Time block key (morning, throughout_day, evening, before_bed, bonus)
 * @returns {Array} Filtered exercises
 */
function getExercisesForTimeBlock(phase, timeBlock) {
    const all = getExercisesForPhase(phase);
    return all.filter((ex) => ex.timeBlock === timeBlock);
}

/**
 * Return exercises for a phase with grouped exercises collapsed into
 * a single descriptor object. Non-grouped exercises pass through unchanged.
 * Each group descriptor has the shape:
 *   { isGroup: true, group: string, groupLabel: string, exercises: Exercise[] }
 */
function getVisibleExercisesForPhase(phase) {
    const all = getExercisesForPhase(phase);
    const result = [];
    const seenGroups = new Set();

    for (const ex of all) {
        if (ex.group) {
            if (!seenGroups.has(ex.group)) {
                seenGroups.add(ex.group);
                const groupMembers = all.filter((e) => e.group === ex.group);
                result.push({
                    isGroup: true,
                    group: ex.group,
                    groupLabel: ex.groupLabel,
                    exercises: groupMembers,
                });
            }
        } else {
            result.push(ex);
        }
    }
    return result;
}

/**
 * Get the category for an exercise by ID.
 * @param {string} id - Exercise ID
 * @returns {string|null} Category string or null if not found
 */
function getCategoryByExerciseId(id) {
    const all = [...exercises.phase1, ...exercises.phase2, ...exercises.phase3];
    const ex = all.find((e) => e.id === id);
    return ex ? ex.category : null;
}

/**
 * Get all unique time blocks that have exercises in a given phase.
 * @param {number} phase
 * @returns {string[]} Array of time block keys in display order
 */
function getTimeBlocksForPhase(phase) {
    const all = getExercisesForPhase(phase);
    const blocks = new Set(all.map((ex) => ex.timeBlock));
    return Object.keys(TIME_BLOCKS)
        .filter((key) => blocks.has(key))
        .sort((a, b) => TIME_BLOCKS[a].order - TIME_BLOCKS[b].order);
}

export {
    exercises,
    TIME_BLOCKS,
    getExercisesForPhase,
    getExercisesForTimeBlock,
    getVisibleExercisesForPhase,
    getCategoryByExerciseId,
    getTimeBlocksForPhase,
};
